# kafka quickstart検証用
# https://kafka.apache.org/quickstart

- hosts: kafka
  become: yes

  vars:
    scala_version: "2.13"
    kafka_version: "3.0.0"

    install_dir: "/opt"
    symlink_name: "kafka"
    kafka_name: "kafka_{{ scala_version }}-{{ kafka_version }}"
    kafka_download_url: "https://dlcdn.apache.org/kafka/{{ kafka_version }}/{{ kafka_name }}.tgz"

  tasks:
 
  - name: Java インストール # 必ずインストールではなくjavaの存在確認をしたい
    yum: name=java-1.8.0-openjdk-devel

  - name: ensure kafka present
    unarchive:
      remote_src: yes
      src: "{{ kafka_download_url }}"
      dest: "{{ install_dir }}"

  - name: ensure symlink present
    file:
      src: "{{ install_dir }}/{{ kafka_name }}"
      dest: "{{ install_dir }}/{{ symlink_name }}"
      mode: 0755
      state: link